# Generated by Django 3.0.2 on 2020-05-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
